### ISSUE TITLE
Update required ibm provider version to `>=1.61.0, <2.0.0` to pull in fix for known issue

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-secrets-manager-private-cert#144]
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4978 was fixed in 1.61.0, so we should bump the required ibm provider version to `>=1.61.0, <2.0.0` (and updates examples as needed too)

**Comment by alex-reiff** [comment]
PR merged, closing
